### ISSUE TITLE
Volume Sampler not working in unity 2017

### ISSUE THREAD

**Issue by 1966256295** [keijiro/Prisma#1]
hello keijiro, i opened VolumeSampler in unity 2017, everything by default, and pressed the "create volume data" button from the sampler object, it reports error:
![image](https://user-images.githubusercontent.com/31345012/29762775-cc98a0a0-8c02-11e7-8cae-78fb151cedf5.png)

**Comment by keijiro** [comment]
You can ignore this error. A new volume data must be created in the Asset directory. Could you check it?

**Comment by 1966256295** [comment]
sorry, it's working fine now.... i missed the mesh collider.
